### ISSUE TITLE
What is a sensitive Powershell command and how do I disable them

### ISSUE THREAD

**Issue by WilliamTIII** [jmau111-org/windows_security#2]
I am familiar with powershell usage and administrative restrictions. I have enabled advanced logging for all devices. I have removed administrative privilege from users, which limits commands to running in user mode. I am not familiar with restricting specific cmdlets, which ones are sensitive, or how to block them. Is removing admin privilege enough, or are there specific commands that users should not be able to execute?

**Comment by jmau111** [comment]
Hi @WilliamTIII ,
Here is a [useful resource for Powershell security](https://media.defense.gov/2022/Jun/22/2003021689/-1/-1/1/CSI_KEEPING_POWERSHELL_SECURITY_MEASURES_TO_USE_AND_EMBRACE_20220622.PDF)

> I have removed administrative privilege from users, which limits commands to running in user mode

Best practice.

>  Is removing admin privilege enough

I see the point of your issue. You can only mitigate the threat, but it's significantly harder to abuse for an attacker. 

You might want to leverage Powershell logging features (e.g., DSBL) to monitor their usage, as it's unlikely a standard user would need it. For example, the `Invoke-WebRequest` command.

As additional measures, I would likely suggest the following:

* rejecting unsigned scripts and restricting script execution
* disable and uninstall deprecated versions of PowerShell
* restricting the execution policy (even if an admin may bypass it for a legitimate purpose `Set-ExecutionPolicy $Policy -Force`)
* checking what commands are accessible to the user by connecting to the endpoint
* learning more advanced mitigations, like [here](https://www.cyber.gov.au/acsc/view-all-content/publications/securing-powershell-enterprise)

**Comment by jmau111** [comment]
I've updated the doc, as "disable" was not the right term, and replace it with "log". I've also added some examples of what I consider unusual commands, even if it can be used for legitimate purposes.

**Comment by jmau111** [comment]
@WilliamTIII hey, thanks for sharing your thoughts. I've waited for some days before closing it.

**Comment by jmau111** [comment]
@WilliamTIII about disabling specific commands, I've found this link https://learn.microsoft.com/en-us/powershell/scripting/learn/remoting/jea/overview?view=powershell-7.3, but I won't mention that in this introduction guide.

Only on [the cheat sheet](https://github.com/jmau111-org/powershell_commands)
