### ISSUE TITLE
Windows still has a (bad) security design at its core

### ISSUE THREAD

**Issue by pauser0000001** [jmau111-org/windows_security#7]
Any file can be renamed to .exe or .com and become immediately capable of being executed (if it has the right bytes in place).
This is the bad security design that is still not fixed. In other OSes, at least you need to give rights of execution, in windows (since the first one up to 11 (11^10, more or less), the problem is still there.

**Comment by jmau111** [comment]
> the problem is still there.

Yes, under some conditions. 

You need the user to run the .exe (or many other formats, like .bat) that will likely be unsigned and spotted by the system. However, the user can still force the exec (e.g., cracked games and software).

You can make Linux users download and exec something with commands like `curl | sh` without `chmod`.

Don't get me wrong. I'm not saying this is not a point of attack, but there are ways to achieve that in other OSes.

**Comment by jmau111** [comment]
Closing this. Thanks for sharing your thoughts.

I use the wrong interface 😖 and missed the GitHub's feature "discussions." Let's see what it does.
